# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = discord --enable-features=UseOzonePlatform --ozone-platform=wayland --start-minimized
exec-once = keepassxc
exec-once = hyprland-per-window-layout